<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div
    class="relative inline-block"
    x-data="initCustomerMenu"
    @keyup.escape="setOpenFalse"
    @click.outside="setOpenFalse"
>
    <button
        type="button"
        id="customer-menu"
        class="text-transparent rounded-full p-1 bg-[#F5F5F9] flex justify-center items-center w-12 md:w-14 h-12 md:h-14"
        @click="toggleOpen"
        :aria-expanded="ariaExpanded"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
        aria-haspopup="true"
    >
        <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M5 21C5 17.134 8.13401 14 12 14C15.866 14 19 17.134 19 21" stroke="#333F1B" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M12 11C14.2091 11 16 9.20914 16 7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7C8 9.20914 9.79086 11 12 11Z" stroke="#333F1B" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>

    </button>
    <nav
        class="z-30 absolute right-0 w-48 sm:w-56 mt-2 py-2 px-1 overflow-auto
            rounded shadow-lg lg:mt-3 bg-container-lighter"
        x-cloak
        x-show="open"
        x-transition
        aria-labelledby="customer-menu"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <?= $block->getChildHtml('header.customer.logged.in.links') ?>
        <?php else: ?>
            <?= $block->getChildHtml('header.customer.logged.out.links') ?>
        <?php endif; ?>
    </nav>
</div>
<script>
    function initCustomerMenu() {
        return {
            open: false,
            toggleOpen() {
                this.open = !this.open;
            },
            setOpenFalse() {
                this.open = false;
            },
            ariaExpanded() {
                return this.open ? 'true' : 'false';
            }
        }
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('initCustomerMenu', initCustomerMenu)
    }, { once: true });
</script>
