<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\LocaleFormatter;



/** @var Toolbar $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="toolbar-sorter sorter flex items-center order-1 col-span-3 sm:col-span-6
        md:col-span-3 lg:col-span-6 justify-end max-md:flex-wrap max-md:justify-center">
    <label class="flex gap-4 items-center">
        <span class="block whitespace-nowrap text-black text-lg md:text-2xl leading-5 md:leading-7.5 font-medium">
            Sort by :
    </span>
        <select data-role="sorter"
                class="form-select sorter-options border-0 focus:border-0 focus:ring-0 text-lg md:text-2xl leading-5 md:leading-7.5 text-light-gray font-medium" 
                aria-label="<?= $escaper->escapeHtmlAttr(__('Sort By')) ?>"
                @change="changeUrl(
                    'product_list_order',
                    $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                    options.orderDefault
                )">
            <?php foreach ($block->getAvailableOrders() as $orderCode => $orderLabel):?>
                <option value="<?= $escaper->escapeHtmlAttr($orderCode) ?>"
                    <?php if ($block->isOrderCurrent($orderCode)): ?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?= $escaper->escapeHtml(__($orderLabel)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </label>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="hidden action sorter-action sort-desc"
           @click.prevent="changeUrl('product_list_dir', 'asc', options.directionDefault)"
        >
            <?= $heroicons->sortAscendingHtml(); ?>
        </a>
    <?php else: ?>
        <a title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="hidden action sorter-action sort-asc"
           @click.prevent="changeUrl('product_list_dir', 'desc', options.directionDefault)"
        >
            <?= $heroicons->sortDescendingHtml(); ?>
        </a>
    <?php endif; ?>

    <div class="text-lg md:text-2xl leading-5 md:leading-7.5 w-max">
        <?= $escaper->escapeHtml(
            __(
                '%1 Products',
                '<span class="toolbar-number">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
            ),
            ['span']
        ) ?>
    </div>
</div>
